### PR TITLE
ci(release.yml): super linter conf added for language PHP

### PR DESCRIPTION
**Pull request by AsifNawaz-cnic**
config for linter > ./github/linters

### CODE REVIEW

**Comment by KaiSchwarz-cnic** [comment]
> config for linter > ./github/linters

ok, great and very useful.

**Comment by KaiSchwarz-cnic** [comment]
In addition for completeness:
* cleanup composer.json "require-dev" section by removing: phpstan/phpstan,  phpcompatibility/php-compatibility, squizlabs/php_codesniffer, roave/security-advisories, dealerdirect/phpcodesniffer-composer-installer
* cleanup composer.json "scripts" block by removing: phpStan, phpCompatibility, phpLint, codeCheck
* cleanup composer.json "config" block completely
* remove folder /scripts
* in the github actions workflow, please also remove `composer run-script phpCompatibility` as this tool wasn't really helpful in the past and the underlying tools are no longer maintained.

Thanks
Kai

**Review by KaiSchwarz-cnic — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by AsifNawaz-cnic** [comment]
ok noted, thanks

**Pull request merged**
